site_name: QuakeView
repo_url: https://github.com/ylseanna/QuakeView
edit_uri: edit/main/docs/content/
copyright: ©2025, QuakeView developers
theme:
  name: readthedocs
  logo: img/quakeview_white_vertical.png
markdown_extensions:
  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.blocks.definition
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.keys
nav:
  - Home: index.md
  - installation.md
  - manual.md
  - dev.md
docs_dir: content
