name: Build releases
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  workflow_dispatch:
  
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "${{ github.repository }} repository has been cloned to the runner."
    
      - run: echo "Branch - ${{ github.ref }}, repository - ${{ github.repository }}."

      - run: echo "Setting up node and python"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.2.0'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r ${{ github.workspace }}/flask/requirements.txt
      - run: pip install pyinstaller
          
      

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - run: echo "Job status is ${{ job.status }}."
